apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docker-oas-bump
  description: ""
spec:
  type: other
  lifecycle: deprecated
  domain: tech-foundation
  system: dev-tools-infra
  owner: architecture
